/**
 * @typedef {Object} SourceItem
 * @property {string} title
 * @property {string} url
 * @property {string} publisher
 */

/**
 * @typedef {Object} VerifyResponse
 * @property {"true" | "false" | "misleading" | "unverifiable"} verdict
 * @property {number} confidence_score
 * @property {SourceItem[]} sources
 */

document.addEventListener('DOMContentLoaded', async () => {
    const states = {
        idle: document.getElementById('state-idle'),
        ready: document.getElementById('state-ready'),
        videoReady: document.getElementById('state-video-ready'),
        videoNoTranscript: document.getElementById('state-video-no-transcript'),
        analyzingVideo: document.getElementById('state-analyzing-video'),
        transcriptReady: document.getElementById('state-transcript-ready'),
        verifying: document.getElementById('state-verifying'),
        result: document.getElementById('state-result'),
        error: document.getElementById('state-error')
    };

    const ui = {
        readyClaimText: document.getElementById('ready-claim-text'),
        verifyBtn: document.getElementById('verify-btn'),
        resultHeader: document.getElementById('result-header'),
        verdictBadge: document.getElementById('verdict-badge'),
        confidenceScore: document.getElementById('confidence-score'),
        resultClaimText: document.getElementById('result-claim-text'),
        sourcesContainer: document.getElementById('sources-container'),
        sourcesList: document.getElementById('sources-list'),
        unverifiableExplainer: document.getElementById('unverifiable-explainer'),
        resetBtn: document.getElementById('reset-btn'),
        retryBtn: document.getElementById('retry-btn'),
        errorMessage: document.getElementById('error-message'),
        videoTranscriptInfo: document.getElementById('video-transcript-info'),
        analyzeVideoBtn: document.getElementById('analyze-video-btn'),
        transcriptStatsInfo: document.getElementById('transcript-stats-info'),
        transcriptAutoInfo: document.getElementById('transcript-auto-info'),
        continueVideoBtn: document.getElementById('continue-video-btn')
    };

    let selectedClaim = "";
    let currentCapability = null;
    let isAnalyzingVideo = false;

    // Switch visible state
    function showState(stateName) {
        Object.values(states).forEach(el => { if(el) el.classList.add('hidden'); });
        if(states[stateName]) states[stateName].classList.remove('hidden');
    }

    // 1. Initialize Extension
    try {
        let [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
        
        // Cannot run script on chrome:// URLs
        if (tab.url.startsWith('chrome://')) {
            showState('idle');
            return;
        }

        // Check for text selection first
        chrome.tabs.sendMessage(tab.id, { action: "getSelectedText" }, (response) => {
            if (chrome.runtime.lastError) {
                console.error("Content script not responding:", chrome.runtime.lastError.message);
                showState('idle');
                return;
            }

            if (response && response.text) {
                selectedClaim = response.text;
                
                // Truncate if insanely long just for UI display
                const displayClaim = selectedClaim.length > 300 
                    ? selectedClaim.substring(0, 300) + "..." 
                    : selectedClaim;
                    
                ui.readyClaimText.textContent = `"${displayClaim}"`;
                showState('ready');
            } else {
                // No text selected. Let's check if there's a video.
                chrome.tabs.sendMessage(tab.id, { action: "getVideoCapability" }, (vidResponse) => {
                    if (chrome.runtime.lastError || !vidResponse || !vidResponse.videoDetected) {
                        showState('idle');
                        return;
                    }
                    
                    if (vidResponse.transcript && (vidResponse.transcript.status === 'available' || vidResponse.transcript.status === 'captions_only')) {
                        currentCapability = vidResponse;
                        if (vidResponse.transcript.isAutoGenerated) {
                            ui.videoTranscriptInfo.textContent = "Based on auto-generated captions.";
                        } else {
                            ui.videoTranscriptInfo.textContent = "Accessible transcript available.";
                        }
                        showState('videoReady');
                    } else {
                        showState('videoNoTranscript');
                    }
                });
            }
        });
    } catch (err) {
        console.error("Failed to read selection:", err);
        showState('idle');
    }

    // 1.5 Handle Video Analysis
    if (ui.analyzeVideoBtn) {
        ui.analyzeVideoBtn.addEventListener('click', async () => {
            if (!currentCapability || isAnalyzingVideo) return;
            isAnalyzingVideo = true;
            
            showState('analyzingVideo');
            
            let [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
            
            chrome.tabs.sendMessage(tab.id, { 
                action: "acquireTranscript", 
                capability: currentCapability
            }, (response) => {
                isAnalyzingVideo = false;
                
                if (chrome.runtime.lastError || !response) {
                    ui.errorMessage.textContent = "Failed to communicate with page.";
                    showState('error');
                    return;
                }
                
                if (response.status === "error") {
                    ui.errorMessage.textContent = response.message || "Failed to retrieve transcript.";
                    showState('error');
                } else if (response.status === "success" && response.transcript) {
                    const segCount = response.transcript.segments ? response.transcript.segments.length : 0;
                    ui.transcriptStatsInfo.textContent = `${segCount} transcript segments`;
                    ui.transcriptAutoInfo.textContent = response.transcript.isAutoGenerated 
                        ? "Based on auto-generated captions" 
                        : "Based on native transcript";
                    showState('transcriptReady');
                }
            });
        });
    }
    
    if (ui.continueVideoBtn) {
        ui.continueVideoBtn.addEventListener('click', () => {
            window.close(); // For Phase 5.3, just close it since claim extraction isn't built yet
        });
    }

    // 2. Handle Verification
    ui.verifyBtn.addEventListener('click', async () => {
        if (!selectedClaim) return;
        
        showState('verifying');

        try {
            // Respecting the actual backend pipeline logic
            const response = await fetch('http://127.0.0.1:8000/api/verify', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ text: selectedClaim })
            });

            if (!response.ok) {
                throw new Error(`Server returned ${response.status}`);
            }

            /** @type {VerifyResponse} */
            const data = await response.json();
            
            renderResult(data);
            showState('result');
            
        } catch (err) {
            console.error("Verification error:", err);
            ui.errorMessage.textContent = "Failed to connect to verification server. Ensure the TruthLens backend is running.";
            showState('error');
        }
    });

    // 3. Render Result Logic
    function renderResult(data) {
        // Reset classes
        ui.verdictBadge.className = 'tl-verdict-badge';
        
        // Display the claim
        const displayClaim = selectedClaim.length > 200 
            ? selectedClaim.substring(0, 200) + "..." 
            : selectedClaim;
        ui.resultClaimText.textContent = `"${displayClaim}"`;

        const verdict = data.verdict;
        const confidenceStr = Math.round(data.confidence_score * 100) + "% confidence";
        ui.confidenceScore.textContent = confidenceStr;

        // Semantic mapping
        if (verdict === 'true') {
            ui.verdictBadge.textContent = "True";
            ui.verdictBadge.classList.add('verdict-true');
        } else if (verdict === 'false') {
            ui.verdictBadge.textContent = "False";
            ui.verdictBadge.classList.add('verdict-false');
        } else if (verdict === 'misleading') {
            ui.verdictBadge.textContent = "Misleading";
            ui.verdictBadge.classList.add('verdict-misleading');
        } else {
            ui.verdictBadge.textContent = "Unverifiable";
            ui.verdictBadge.classList.add('verdict-unverifiable');
            // Hide confidence for unverifiable since it's 0.0
            ui.confidenceScore.textContent = "Opinion or insufficient evidence";
        }

        // Render sources
        ui.sourcesList.innerHTML = '';
        if (data.sources && data.sources.length > 0) {
            ui.sourcesContainer.classList.remove('hidden');
            ui.unverifiableExplainer.classList.add('hidden');
            
            data.sources.forEach(source => {
                const a = document.createElement('a');
                a.className = 'tl-source-card';
                a.href = source.url;
                a.target = '_blank';
                a.rel = 'noopener noreferrer';
                
                const publisherDiv = document.createElement('div');
                publisherDiv.className = 'tl-source-publisher';
                publisherDiv.innerHTML = `
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>
                    ${source.publisher || new URL(source.url).hostname}
                `;
                
                const titleDiv = document.createElement('div');
                titleDiv.className = 'tl-source-title';
                titleDiv.textContent = source.title;
                
                a.appendChild(publisherDiv);
                a.appendChild(titleDiv);
                ui.sourcesList.appendChild(a);
            });
        } else {
            ui.sourcesContainer.classList.add('hidden');
            ui.unverifiableExplainer.classList.remove('hidden');
        }
    }

    // 4. Utility Buttons
    ui.resetBtn.addEventListener('click', () => {
        window.close(); // Extension pattern: close popup to "verify another"
    });

    ui.retryBtn.addEventListener('click', () => {
        showState('ready'); // Go back to ready to try again
    });

    // 5. Restore Legacy Feature: Highlight Loaded Language
    const explainBtn = document.getElementById('explain-btn');
    if (explainBtn) {
        explainBtn.addEventListener('click', async () => {
            const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
            if (!tab.url.startsWith('chrome://')) {
                chrome.tabs.sendMessage(tab.id, { action: "triggerExplainer" });
                window.close(); // Close the popup so the user can see the highlights
            }
        });
    }
});